name: dispatch_suite
description: The dispatch app and server.
version: 0.1.0
# repository: https://github.com/weasdown/dispatch
publish_to: none

workspace:
  - app
  - server

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
