name: server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

resolution: workspace
environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  dispatch: ^0.1.0+1
  google_maps_flutter: ^2.12.2
  intl: ^0.20.2
  latlng: ^2.0.7
  logging: ^1.3.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
